# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/notification.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/notification.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bmessages/notification.proto\"b\n\x11\x45mailNotification\x12\x12\n\nrecipients\x18\x01 \x03(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\x04html\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_htmlb\x06proto3'
)




_EMAILNOTIFICATION = _descriptor.Descriptor(
  name='EmailNotification',
  full_name='EmailNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipients', full_name='EmailNotification.recipients', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='EmailNotification.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='EmailNotification.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='html', full_name='EmailNotification.html', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_html', full_name='EmailNotification._html',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=31,
  serialized_end=129,
)

_EMAILNOTIFICATION.oneofs_by_name['_html'].fields.append(
  _EMAILNOTIFICATION.fields_by_name['html'])
_EMAILNOTIFICATION.fields_by_name['html'].containing_oneof = _EMAILNOTIFICATION.oneofs_by_name['_html']
DESCRIPTOR.message_types_by_name['EmailNotification'] = _EMAILNOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailNotification = _reflection.GeneratedProtocolMessageType('EmailNotification', (_message.Message,), {
  'DESCRIPTOR' : _EMAILNOTIFICATION,
  '__module__' : 'messages.notification_pb2'
  # @@protoc_insertion_point(class_scope:EmailNotification)
  })
_sym_db.RegisterMessage(EmailNotification)


# @@protoc_insertion_point(module_scope)
