# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/persistence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amessages/persistence.proto\"0\n\rCreateAccount\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x0c\"~\n\x11\x43reateCertificate\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x17\n\x0fpem_private_key\x18\x02 \x01(\x0c\x12\x10\n\x08pem_cert\x18\x03 \x01(\x0c\x12\x11\n\tpem_chain\x18\x04 \x01(\x0c\x12\x1a\n\x12\x65ncrypted_password\x18\x05 \x01(\x0c\":\n\x11RevokeCertificate\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.persistence_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEACCOUNT']._serialized_start=30
  _globals['_CREATEACCOUNT']._serialized_end=78
  _globals['_CREATECERTIFICATE']._serialized_start=80
  _globals['_CREATECERTIFICATE']._serialized_end=206
  _globals['_REVOKECERTIFICATE']._serialized_start=208
  _globals['_REVOKECERTIFICATE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
