# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/persistence.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/persistence.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1amessages/persistence.proto\"0\n\rCreateAccount\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x0c\"~\n\x11\x43reateCertificate\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x17\n\x0fpem_private_key\x18\x02 \x01(\x0c\x12\x10\n\x08pem_cert\x18\x03 \x01(\x0c\x12\x11\n\tpem_chain\x18\x04 \x01(\x0c\x12\x1a\n\x12\x65ncrypted_password\x18\x05 \x01(\x0c\":\n\x11RevokeCertificate\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3'
)




_CREATEACCOUNT = _descriptor.Descriptor(
  name='CreateAccount',
  full_name='CreateAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='CreateAccount.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='CreateAccount.password', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=78,
)


_CREATECERTIFICATE = _descriptor.Descriptor(
  name='CreateCertificate',
  full_name='CreateCertificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='CreateCertificate.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pem_private_key', full_name='CreateCertificate.pem_private_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pem_cert', full_name='CreateCertificate.pem_cert', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pem_chain', full_name='CreateCertificate.pem_chain', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encrypted_password', full_name='CreateCertificate.encrypted_password', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=206,
)


_REVOKECERTIFICATE = _descriptor.Descriptor(
  name='RevokeCertificate',
  full_name='RevokeCertificate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='RevokeCertificate.serial_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='RevokeCertificate.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['CreateAccount'] = _CREATEACCOUNT
DESCRIPTOR.message_types_by_name['CreateCertificate'] = _CREATECERTIFICATE
DESCRIPTOR.message_types_by_name['RevokeCertificate'] = _REVOKECERTIFICATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateAccount = _reflection.GeneratedProtocolMessageType('CreateAccount', (_message.Message,), {
  'DESCRIPTOR' : _CREATEACCOUNT,
  '__module__' : 'messages.persistence_pb2'
  # @@protoc_insertion_point(class_scope:CreateAccount)
  })
_sym_db.RegisterMessage(CreateAccount)

CreateCertificate = _reflection.GeneratedProtocolMessageType('CreateCertificate', (_message.Message,), {
  'DESCRIPTOR' : _CREATECERTIFICATE,
  '__module__' : 'messages.persistence_pb2'
  # @@protoc_insertion_point(class_scope:CreateCertificate)
  })
_sym_db.RegisterMessage(CreateCertificate)

RevokeCertificate = _reflection.GeneratedProtocolMessageType('RevokeCertificate', (_message.Message,), {
  'DESCRIPTOR' : _REVOKECERTIFICATE,
  '__module__' : 'messages.persistence_pb2'
  # @@protoc_insertion_point(class_scope:RevokeCertificate)
  })
_sym_db.RegisterMessage(RevokeCertificate)


# @@protoc_insertion_point(module_scope)
